spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  flyway:
    schemas: ${DB_SCHEMA:collector}
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
rating:
  relative:
    max: 30000
    min: 0
    scoreDistribution:
      COMMON:
        1: 100
        2: 70
        3: 40
        4: 20
        5: -20
        6: -40
        7: -70
        8: -100
  simple:
    max: 30000
    min: 0
    scoreDistribution:
      COMMON:
        1: 100
        2: 75
        3: 50
        4: 25
        5: -25
        6: -50
        7: -75
        8: -100
  competitive:
    max: 30000
    min: 0
    scoreDistribution:
      COMMON:
        1: 100
        2: 70
        3: 25
        4: 0
        5: -25
        6: -50
        7: -75
        8: -100
