openapi: 3.0.0
info:
  version: 1.1.0
  title: Collector API
  description: Collector API

servers:
  - url: http://localhost:8080

paths:
  /matches:
    post:
      operationId: saveMatch
      description: save info about started match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Match'
                - $ref: '#/components/schemas/MatchStart'
      responses:
        '200':
          description: match start info saved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    put:
      operationId: updateMatch
      description: update info about started match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchUpdate'
      responses:
        '200':
          description: match update info saved
components:
  schemas:
    Error:
      type: object
      properties:
        time:
          type: string
          format: date-time
        shortMessage:
          description: developer defined error message
          type: string
        message:
          description: java error message and stacktrace
          type: string
    Match:
      type: object
      properties:
        id:
          type: string
          format: uuid
    MatchStart:
      type: object
      properties:
        playersSteamId:
          type: array
          items:
            properties:
              steamId:
                type: string
    MatchUpdate:
      type: object
      properties:
        players:
          type: object
    Player:
      type: object
      properties:
        id:
          type: string
          format: uuid
        steamId:
          type: string
        simpleMmr:
          type: integer
        competitiveMmr:
          type: integer
        relativeMmr:
          type: integer
        settings:
          type: array
          items:
            $ref: '#/components/schemas/PlayerSetting'
        npcAlibitySets:
          type: array
          items:
            $ref: '#/components/schemas/NpcAbilitySet'
    PlayerSetting:
      type: object
      properties:
        name:
          type: string
        value:
          type: integer
    NpcAbilitySet:
      type: object
      properties:
        npcName:
          type: string
        options:
          type: array
          items:
            type: integer