openapi: 3.0.0
info:
  version: 1.1.0
  title: Collector API
  description: Collector API

servers:
  - url: http://localhost:8080

paths:
  /matches:
    post:
      operationId: saveMatch
      description: save info about started match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/MatchStart.yaml#/SteamIds'
      responses:
        '200':
          description: match start info saved
          content:
            application/json:
              schema:
                $ref: 'components/MatchStart.yaml#/MatchStart'
    put:
      operationId: updateMatch
      description: update info about started match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/MatchUpdate.yaml#/MatchUpdate'
      responses:
        '200':
          description: match update info saved
components:
  schemas:
    Error:
      type: object
      properties:
        time:
          type: string
          format: date-time
        shortMessage:
          description: developer defined error message
          type: string
        message:
          description: java error message and stacktrace
          type: string